name: deploy-on-merge

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-main
  cancel-in-progress: true

env:
  PROJECT_ID: jam-poker

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Functions dependencies
        run: npm --prefix functions install

      - name: Build Cloud Functions
        run: npm --prefix functions run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JAM_POKER }}

      - name: Deploy Functions and Hosting to production
        run: firebase deploy --only functions,hosting --project "$PROJECT_ID" --non-interactive --force
