name: Firebase Hosting Preview (stub)

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Preview stub
        run: |
          echo "Preview workflow temporarily stubbed to fix YAML errors."
          echo "Real deploys still handled by deploy-on-merge."
