name: Deploy Firebase (Functions + Hosting) on merge
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # needed for google-github-actions/auth
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JAM_POKER }}
      - name: Install Firebase CLI
        run: npm i -g firebase-tools
      - name: Deploy Functions + Hosting + Rules
        run: firebase deploy --only functions,hosting,firestore:rules --project jam-poker --non-interactive --force
